add component property that is called when selection is changed
silevis/reactgrid pull request #184
Opened 2023-06-28 18:13 UTC by alonshmiel

I changed publicModel file ("PLEASE ASK ARCHITECT BEFORE INTRODUCING ANY CHANGE IN THIS FILE").

It's a feature request:
When a range is selected, the users want to know the selection.

The issues are:
https://github.com/silevis/reactgrid/issues/151
https://github.com/silevis/reactgrid/issues/119

2023-07-01 06:51 UTC, fellmann requested changes, later dismissed
I tested it and I think many cases are missing, for example:
- Cell selection changed after context menu open
- Cell selection changed after key events (enter, arrows keys, shift + arrow keys ...)
- Selection changes after inserting from clipboard, using the fill handle, 
and probably some more.

Also, I came to think we should differentiate between onSelectionStarted, onSelectionChanged, and onSelectionFinished. For some applications, (like mine) it is required be informed about selection changed directly after mouse down, and not just at mouse up.

2023-08-08 11:30 UTC, MichaelMatejko commented
let's start with OnSeclectionChanging and OnSelectionChanged - a schema we used earlier.
If additional events are needed we will add them on demand.
Done is better than perfect. 

For the new version 5 we discussed to add events such that somebody can "override" the default behavior (of any functionality)  by copying and changing the code provided by reactgrid. Very similar to regular html components where you can preventDefault() and react as you like. 

@DLowHP will add the "changing" event and we will  include the PR into dev.

2023-08-16 15:13 UTC, DLowHP commented
I added `onSelectionChanging` handler, moved the `onSelectionChanged` call to CellSelectionBehavior instead of PointerEventsController and implemented both functions in other places to handle different cases. I'm not 100% sure it handles every case so your feedback will be highly appreciated.

These changes also mean that every time focused cell changes one or both selection handlers are called depending on focus change reason - I'm pointing this out because I'm not sure whether that's an issue or not.

2023-08-22 11:14 UTC, MichaelMatejko approved these changes

2023-08-22 11:19 UTC, merged