When supporting the need for double check, a carriage return is requi…
silevis/reactgrid pull request #292
Opened 2023-12-21 03:02 UTC by qiufeihong2018

…red in a single text cell and onCellsChanged is triggered, changes become an array of one element, but a two-element array #289

resolved

<img width="1466" alt="image" src="https://github.com/silevis/reactgrid/assets/36500514/b7bbe320-b675-4106-bf22-e0ab82ea66db">

2024-01-03 13:19 UTC, Michota commented on src/lib/Functions/focusLocation.ts
> +      !(keyCode === keyCodes.ENTER)
More clear me.
```suggestion
      keyCode !== keyCodes.ENTER
```

2024-01-03 13:23 UTC, Michota requested changes
I would change the way it checks the `Enter` keycode. Instead of checking for a keycode, i would suggest to pass boolean, that is based on if `Enter` was clicked, something like `isEnter = keyCode === keyCodes.Enter`, which would be more clear in my opinion, but its not necessary.

2024-01-03 13:24 UTC, Michota approved these changes

2024-01-03 13:26 UTC, merged

2024-01-09 22:34 UTC, mitchell-robinson commented
@Michota I'm not sure this is fixed properly, I still receive two change events when hitting `Enter`

In the video below, the first cell I edit, I hit `Enter` -- notice the array with two events where I'm logging the `CellChange[]` array passed to the `onCellsChanged` handler.

When I edit the second cell, I blur to another cell -- notice the single event logged.

https://github.com/silevis/reactgrid/assets/101780654/1680262b-d866-4583-8602-ec0fb38c20b7

Running latest 4.1.3

2024-01-10 03:42 UTC, qiufeihong2018 commented
@mitchell-robinson 
Surprisingly, I did see the correct result in the example. When you updated to 4.1.3, this problem still occurred. Could you please repeat it in src/test/TestGrid.tsx? Or take a look at the faulty code in your project in CodePen?

2024-01-10 20:45 UTC, mitchell-robinson commented
@qiufeihong2018 @Michota
I was unable to reproduce the error in `src/test/TestGrid.tsx`.

However, I created two fresh projects, and used the [Getting Started example](https://reactgrid.com/docs/4.0/1-getting-started/) from the docs to set up a quick reproducible example:

https://github.com/mitchell-robinson/cra-ts-reactgrid-test
https://github.com/mitchell-robinson/nextjs-reactgrid-test

Both just setup and run the example from the docs, and console log the `changes` from the onCellsChanged handler. I'm seeing 2 events when hitting enter here, are either of you able to pull those repos, run, and reproduce?

thanks in advance

2024-01-25 19:43 UTC, kateEcobb commented
This fix hasn't been released yet, so it shouldn't be marked as resolved. Is there a plan to release this soon?

2024-02-07 14:37 UTC, Michota commented
@kateEcobb im working on v5 now.
After releasing v5-alpha i will come back to v4, and will fix this issue.