Correctly copy & paste data with context menu, and handle number notion that is based on locale
silevis/reactgrid pull request #296
Opened 2023-12-28 13:03 UTC by Michota

## Context menu copy-pasting
- Fix issue #282 
- New function getRowsFromClipboard (asynchronous):
  - returns Compatible<Cell>[], which can be later used in pasteData function.
### Parse number with respecting locale number notion
Respect the locale settings for user-supplied numerical data, whether pasted or entered manually.
- New function parseLocaleNumber
  - Locale can be provided manually (as string). If this does not happen, the function will get it from the browser itself.
  - returns number.
```ts
function parseLocaleNumber(stringNumber: string, locale = getNavigatorLanguage()): number
```
```tsx
parseLocaleNumber("123456,78") // returns 123456.78
parseLocaleNumber("1 234 56,78", "pl-PL") // returns 123456.78
parseLocaleNumber("1,234,56.78", "en-US") // returns 123456.78

2023-12-28 17:00 UTC, DLowHP requested changes

2023-12-28 17:00 UTC, DLowHP commented on package.json
> -      "pre-push": "if git-branch-is develop; then npx run-s eslint run:all:tests; fi"
I believe this was commited by mistake as I think we should keep this line.

2023-12-28 17:00 UTC, DLowHP commented on src/lib/Functions/getNavigatorLanguage.ts
> +  "en-US";
Does this need to be so complicated? I think that `navigator.language` should be sufficient, but I might be wrong?

2023-12-28 17:00 UTC, DLowHP commented on tsconfig.json
> +    "noEmitOnError": false,
Is this _explicitly_ needed? [The docs](https://www.typescriptlang.org/tsconfig#noEmitOnError:~:text=This%20defaults%20to%20false%2C%20making%20it%20easier%20to%20work%20with%20TypeScript%20in%20a%20watch%2Dlike%20environment%20where%20you%20may%20want%20to%20see%20results%20of%20changes%20to%20your%20code%20in%20another%20environment%20before%20making%20sure%20all%20errors%20are%20resolved.) say that this is `false` by default.

2023-12-29 10:33 UTC, Michota commented on package.json
> -      "pre-push": "if git-branch-is develop; then npx run-s eslint run:all:tests; fi"
Yeah, You are right. But for some reason i can't push if this hook is there, even if i try to push it to non-develop branch...

2023-12-29 10:39 UTC, Michota commented on src/lib/Functions/getNavigatorLanguage.ts
> +  "en-US";
Oh, you are right, navigator.language is basically the same as navigator.language**s**[0]

2023-12-29 13:57 UTC, DLowHP commented on package.json
> -      "pre-push": "if git-branch-is develop; then npx run-s eslint run:all:tests; fi"
Will have to look into this some time... I'll add this to the backlog!

2023-12-29 13:58 UTC, DLowHP approved these changes

2023-12-29 13:59 UTC, merged