Follow focused cell
silevis/reactgrid pull request #321
Opened 2024-01-16 16:35 UTC by Michota

**Description:** If focus will be changed due to user clicking arrow keys, react-grid will follow it by changing view, so it will be visible.

- It won't use scrollbars that are attached to other windows.
- It will jump to focused cell if it is not visible.

## Possible changes
- Make focused cell stay at the border of sticky-cell panes, so the adjacent non-sticky cell will be invisible. It can be done thanks to `detectColision` which will return `overlapX` & `overlapY` values, that could be used for re-calculating distance between `focusedCell` and sticky-cell pane, so they will be pixel-perfectly aligned (as on image below).
![Feature preview](https://github.com/silevis/reactgrid/assets/109215822/559646d7-ec0f-492a-912c-0dd851fe69b8)

## Known bugs
- Newly focused cell wont be fully visible (may be covered by sticky pane) **if direction focus gone is different from the direction that cell spans** to. It's a minor bug though, and can should be easily fixed in the future, after future updates will be done.
Bug preview:
![Described bug preview](https://github.com/silevis/reactgrid/assets/109215822/434de80b-12d8-488b-8b85-b067fea6a712)

2024-01-24 12:49 UTC, DLowHP requested changes

2024-01-24 12:49 UTC, DLowHP commented on src/utils/getDistanceBetweenHTMLElements.ts
> +  }
Is this check really needed?

2024-01-24 12:49 UTC, DLowHP commented on src/utils/getDistanceBetweenHTMLElements.ts
> +  };
I believe we can just use the `window` global
```suggestion
  return {
    top: rect.top + window.scrollY,
    left: rect.left + window.scrollY,
  };
```

2024-01-25 10:20 UTC, MichaelMatejko approved these changes

2024-01-25 14:48 UTC, DLowHP approved these changes

2024-01-25 14:50 UTC, merged