Improvement/public model docs comments
silevis/reactgrid pull request #34
Opened 2020-10-12 06:54 UTC by patryk0493

2020-10-12 10:27 UTC, myskamil commented on src/lib/CellTemplates/keyCodeCheckings.ts
> + * Checks that the pressed key's `keyCode` is is one of alphanumeric keys
* Checks that the pressed key's `keyCode` is one of alphanumeric keys

2020-10-12 10:46 UTC, myskamil commented on src/lib/Model/PublicModel.ts
> + * `Change` interface represents a particullar change on a single cell on the cell template.
* `Change` interface represents a particular change on a single cell on the cell template.

2020-10-12 10:49 UTC, myskamil commented on src/lib/Model/PublicModel.ts
> +     * @param isInEditMode Flag is set to `true`,if cell is rendered in edit mode
isInEditMode Flag is set to `true`, if cell is rendered in edit mode

2020-10-12 10:54 UTC, myskamil requested changes
Looks very nice, just small mistakes 👍

2020-10-13 06:23 UTC, patryk0493 reviewed
Misspellings fixed

2020-10-13 06:33 UTC, merged